language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer install

script:
    - mkdir -p storage/coverage
    - ./vendor/bin/phpunit --configuration phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls